FROM gliderlabs/alpine:3.2

RUN apk-install curl bash
RUN curl -sL https://github.com/progrium/basht/releases/download/v0.1.0/basht_0.1.0_Linux_x86_64.tgz \
    | tar xvz -C /usr/local/bin
RUN curl -sL https://get.docker.com/builds/Linux/x86_64/docker-1.7.1 \
      > /usr/local/bin/docker \
    && chmod +x /usr/local/bin/docker
CMD /bin/bash
